### ISSUE TITLE
Is it safe to upgrade to OWIN-MixedAuth?

### ISSUE THREAD

**Issue by LESARQ** [MohammadYounes/MVC5-MixedAuth#41]
Hey again,

I've been using this branch for a few months and everything is working.
But it seems that this branch will not receive updates anymore, so i want to start using OWIN-MixedAuth branch.

However, i made some modifications on my code and i know i need to merge them locally with your OWIN solution.

But, are there any MAIN differences that may break my application?

**Comment by MohammadYounes** [comment]
Hi,

[MVC5-MixedAuth] is more of a proof of concept that makes mixed authentication appear as if it's an external provider. 

Using [OWIN-MixedAuth] requires less custom code, because its modular, integrates with the authentication pipeline and works seamlessly with other authentication providers.

Thanks.

[OWIN-MixedAuth]: https://github.com/MohammadYounes/OWIN-MixedAuth
[MVC5-MixedAuth]: https://github.com/MohammadYounes/MVC5-MixedAuth

**Comment by LESARQ** [comment]
I see, but i'm afraid that if I start using the new branch it will break anything.
That' why I was asking if there are any breaking changes between the two branches

**Comment by MohammadYounes** [comment]
Behavior wise, there are none.

**Comment by LESARQ** [comment]
Good!

I'll try to update my application, I'll say something in next week. 
If it fails I'll report it, if not I'll stay in silence.

Thank you,
Regards
