### ISSUE TITLE
Application check for windows authentication

### ISSUE THREAD

**Issue by MrBeezel** [MohammadYounes/MVC5-MixedAuth#45]
Hello,
I found this repository by chance and I think it can help me for what I want to design.
I comment on my idea:
I want to design a windows application that will connect to a web service through active directory. But also, i want to be able to access this web service through the browser through form authentication.
My question is: 
To what path would I have to send the authentication request from my application? 
Because I have been trying to send it to the login page but I always get a 500 error.

I appreciate your support

**Comment by MohammadYounes** [comment]
Hello, 

This project ([MVC5-MixedAuth]) is more of a proof of concept that makes mixed authentication appear as if it's an external provider.  You need to switch to [OWIN-MixedAuth], because its modular, integrates with the authentication pipeline and works seamlessly with other authentication providers.

[OWIN-MixedAuth]: https://github.com/MohammadYounes/OWIN-MixedAuth
[MVC5-MixedAuth]: https://github.com/MohammadYounes/MVC5-MixedAuth

To authenticate users from you Windows App, You need to hit the authorize end point to get an access token, then use it along with your Api calls. See the sample project named [SPA](https://github.com/MohammadYounes/OWIN-MixedAuth/tree/master/src/SPA) (The access token is retrieved [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L40-L53) and the Authorize end point is defined [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L26)).

For forms authentication you need to use `Password Login Flow` on the [token endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L25) and for windows authentication you need to use `External Login Flow`  on the [authorization endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L26). 

See http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api for more details

Thanks.

**Comment by MohammadYounes** [comment]
Hello, 

This project ([MVC5-MixedAuth]) is more of a proof of concept that makes mixed authentication appear as if it's an external provider.  You need to switch to [OWIN-MixedAuth], because its modular, integrates with the authentication pipeline and works seamlessly with other authentication providers.

[OWIN-MixedAuth]: https://github.com/MohammadYounes/OWIN-MixedAuth
[MVC5-MixedAuth]: https://github.com/MohammadYounes/MVC5-MixedAuth

To authenticate users from your Windows App, You need to hit the authorize end point to get an access token, then use it along with your Api calls. See the sample project named [SPA](https://github.com/MohammadYounes/OWIN-MixedAuth/tree/master/src/SPA) (The access token is retrieved [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L40-L53) and the Authorize end point is defined [here](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L26)).

For forms authentication you need to use `Password Login Flow` on the [token endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L25) and for windows authentication you need to use `External Login Flow`  on the [authorization endpoint](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L26). 

See http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api for more details

Thanks.
